import type { Metadata } from "next";
import "./globals.css";
import Nav from './component/nav'
import Footer from "./footer/page";
import {Archivo} from 'next/font/google'

const archivo = Archivo({
  weight:['400'],
  subsets:['latin'],
}) ;



export const metadata: Metadata = {
  title: "Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       className={archivo.className}
      >
        <Nav/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
